sudo: false
language: cpp
compiler:
    - clang
    - gcc

addons:
  apt:
    packages:
    - libgtest-dev

env:
    - CFLAGS="-Werror" CXXFLAGS="-Werror"

before_install:
    - mkdir gtest-build
    - mkdir build/
    - pushd gtest-build
    - cmake /usr/src/gtest
    - make
    - popd

before_script:
    - cd build/
    - CMAKE_LIBRARY_PATH=../gtest-build/ cmake ../tests

script:
    - make
    - ./run_tests
