sudo: required
dist: trusty
language: cpp
compiler:
    - clang
    - gcc

addons:
  apt:
    packages:
    - libgtest-dev
    - g++-multilib
    - gcc-multilib
    - gcc-avr
    - avr-libc

env:
    - CFLAGS="-Werror" CXXFLAGS="-Werror"

script:
    # Building and running unit tests
    - mkdir build
    - cd build
    - cmake ../tests
    - make
    - ./run_tests
    - cd ..
    # Building the AVR driver (TODO: skip this during Clang build)
    - mkdir build-avr
    - cd build-avr
    - cmake ../drivers/avr
    - make
